### PR TITLE
Add information about testing with the browser

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
Awesome! 

I have a question. If I run kinit in a shell, do I need to launch the browser from that shell?

**Comment by sberyozkin** [comment]
Hi @cescoffier No, as long both the browser and `kinit` work with the same KDC config they can be started independently. If this is a default system wide KRB config or some custom one pointed to in `~/.bashrc` then one can start a browser as usual; I had to start the browser from the shell when I was verifying it works with the container started by `Dev Services for Kerberos` - since `KRB5_CONFIG` points to the file with the current container's mapped ports.

**Comment by sberyozkin** [comment]
@cescoffier I'll update PR a bit to highlight the importance of the same configuration be visible to both the browser and KRB tools

**Comment by cescoffier** [comment]
Thanks!

**Comment by sberyozkin** [comment]
@cescoffier Thanks, have just pushed a minor update to clarify both the browser and `kinit` have to see the same config

**Pull request merged**
