### PR TITLE
Bump to Quarkus 3.12.3

### LINKED ISSUE #119: Build does not work (Quarkus 3.11.1) :  java.lang.NoSuchFieldError: type at io.quarkiverse.kerberos.deployment.KerberosBuildStep.register2
Hello,

I just cannot use the extension as I get a build error when starting my application.
I'm using quarkus 3.11.1. The project has been generated from code.quarkus.io by selecting Rest and Kerberos extensions.

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] --------------< com.inetum.bd.kerberos:kerberos-test-app >--------------
> [INFO] Building kerberos-test-app 1.0.0-SNAPSHOT
> [INFO]   from pom.xml
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- quarkus:3.11.1:dev (default-cli) @ kerberos-test-app ---
> [INFO] Invoking resources:3.3.1:resources (default-resources) @ kerberos-test-app
> [INFO] Copying 1 resource from src\main\resources to target\classes
> [INFO] Invoking quarkus:3.11.1:generate-code (default) @ kerberos-test-app
> [INFO] Invoking compiler:3.12.1:compile (default-compile) @ kerberos-test-app
> [INFO] Recompiling the module because of added or removed source files.
> [INFO] Compiling 3 source files with javac [debug release 17] to target\classes
> [INFO] Invoking resources:3.3.1:testResources (default-testResources) @ kerberos-test-app
> [INFO] skip non existing resourceDirectory C:\dev\git\kerberos-test-app\src\test\resources
> [INFO] Invoking quarkus:3.11.1:generate-code-tests (default) @ kerberos-test-app
> [INFO] Invoking compiler:3.12.1:testCompile (default-testCompile) @ kerberos-test-app
> [INFO] Recompiling the module because of changed dependency.
> [INFO] Compiling 2 source files with javac [debug release 17] to target\test-classes
> Listening for transport dt_socket at address: 5005
> Press [e] to edit command line args (currently ''), [h] for more options>
> 2024-06-07 12:32:28,211 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
> 2024-06-07 12:32:28,589 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 	[error]: Build step io.quarkiverse.kerberos.deployment.KerberosBuildStep#register2 threw an exception: java.lang.NoSuchFieldError: type
> 	at io.quarkiverse.kerberos.deployment.KerberosBuildStep.register2(KerberosBuildStep.java:59)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
> 
> 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
> 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
> 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
> 	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
> 	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
> 	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
> 	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
> 	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
> 	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
> 	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
> Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 	[error]: Build step io.quarkiverse.kerberos.deployment.KerberosBuildStep#register2 threw an exception: java.lang.NoSuchFieldError: type
> 	at io.quarkiverse.kerberos.deployment.KerberosBuildStep.register2(KerberosBuildStep.java:59)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
> 
> 	at io.quarkus.builder.Execution.run(Execution.java:123)
> 	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
> 	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
> 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
> 	... 9 more
> Caused by: java.lang.NoSuchFieldError: type
> 	at io.quarkiverse.kerberos.deployment.KerberosBuildStep.register2(KerberosBuildStep.java:59)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)

pom.xml dependencies : 

`    <modelVersion>4.0.0</modelVersion>
    <groupId>com.inetum.bd.kerberos</groupId>
    <artifactId>kerberos-test-app</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <compiler-plugin.version>3.12.1</compiler-plugin.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.11.1</quarkus.platform.version>
        <skipITs>true</skipITs>
        <surefire-plugin.version>3.2.5</surefire-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.kerberos</groupId>
            <artifactId>quarkus-kerberos</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>`

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #119

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
The CI must be adapted as we do not have Java 17 yet

**Comment by gastaldi** [comment]
Also the build fails with `java.lang.IllegalAccessException: class io.quarkiverse.kerberos.runtime.KerberosRecorder cannot access class sun.security.jgss.SunProvider (in module java.security.jgss) because module java.security.jgss does not export sun.security.jgss to unnamed module @21bcffb5`

Now how do we declare this module? 🤔

**Comment by sberyozkin** [comment]
Hey @gastaldi, thanks a million for looking after it

**Comment by gastaldi** [comment]
This PR requires https://github.com/quarkusio/quarkus/pull/41836 to be in a Quarkus release before passing

**Pull request merged**
